name: "3-Deployment to S3"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Target environment for deployment
        options:
          - Staging
          - Production

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          # sudo apt-get update
          # sudo apt-get install -y awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build static site (if applicable)
        if: ${{ inputs.environment == 'Production' || inputs.environment == 'Staging' }}
        run: |
          # Add your build commands here if needed, e.g.:
          # npm install
          # npm run build
          echo "No build step defined, skipping."

      - name: Sync static files to S3
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          # Adjust the source directory if your build output is not ./public
          aws s3 sync ./public s3://$S3_BUCKET_NAME --delete --acl public-read

